export const NATIONALITY_OPTIONS = [
  "ITALIA",
  "AFGHANISTAN",
  "ALBANIA",
  "ALGERIA",
  "ANDORRA (Principato di)",
  "ANGOLA",
  "ANTIGUA E BARBUDA",
  "ARABIA SAUDITA",
  "ARGENTINA",
  "ARMENIA",
  "AUSTRALIA",
  "AUSTRIA",
  "AZERBAIJAN",
  "BAHAMAS",
  "BAHREIN",
  "BANGLADESH",
  "BARBADOS",
  "BELARUS",
  "BELGIO",
  "BELIZE",
  "BENIN",
  "BOLIVIA",
  "BOSNIA ERZEGOVINA",
  "BOTSWANA",
  "BRASILE",
  "BRUNEI",
  "BULGARIA",
  "BURKINA FASO",
  "BURUNDI",
  "CABO VERDE",
  "CAMBOGIA",
  "CAMERUN",
  "CANADA",
  "CIAD",
  "CILE",
  "CINA",
  "CIPRO",
  "COLOMBIA",
  "COMORE",
  "CONGO",
  "CONGO (R.D)",
  "COREA (R.D.P.)",
  "COREA",
  "COSTA D’AVORIO",
  "COSTA RICA",
  "CROAZIA",
  "CUBA",
  "DANIMARCA",
  "DOMINICA",
  "ECUADOR",
  "EGITTO",
  "EL SALVADOR",
  "EMIRATI ARABI UNITI",
  "ERITREA",
  "ESTONIA",
  "ESWATINI",
  "ETIOPIA",
  "FEDERAZIONE RUSSA",
  "FIGI",
  "FILIPPINE",
  "FINLANDIA",
  "FRANCIA",
  "GABON",
  "GAMBIA",
  "GEORGIA",
  "GERMANIA",
  "GHANA",
  "GIAMAICA",
  "GIAPPONE",
  "GIBUTI",
  "GIORDANIA",
  "GRECIA",
  "GRENADA",
  "GUATEMALA",
  "GUINEA",
  "GUINEA BISSAU",
  "GUINEA EQUATORIALE",
  "GUYANA",
  "HAITI",
  "HONDURAS",
  "INDIA",
  "INDONESIA",
  "IRAN",
  "IRAQ",
  "IRLANDA",
  "ISLANDA",
  "ISOLE COOK",
  "ISOLE MARSHALL",
  "ISOLE SALOMONE",
  "ISRAELE",
  "KAZAKHSTAN",
  "KENYA",
  "KYRGHIZISTAN",
  "KIRIBATI",
  "KOSOVO",
  "KUWAIT",
  "LAOS",
  "LESOTHO",
  "LETTONIA",
  "LIBANO",
  "LIBERIA",
  "LIBIA",
  "LIECHTENSTEIN",
  "LITUANIA",
  "LUSSEMBURGO",
  "MACEDONIA DEL NORD",
  "MADAGASCAR",
  "MALAWI",
  "MALAYSIA",
  "MALDIVE",
  "MALI",
  "MALTA",
  "MAROCCO",
  "MAURITANIA",
  "MAURITIUS",
  "MESSICO",
  "MOLDOVA",
  "MONACO",
  "MONGOLIA",
  "MONTENEGRO",
  "MOZAMBICO",
  "MYANMAR",
  "NAMIBIA",
  "NAURU",
  "NEPAL",
  "NICARAGUA",
  "NIGER",
  "NIGERIA",
  "NIUE",
  "NORVEGIA",
  "NUOVA ZELANDA",
  "OMAN",
  "PAESI BASSI",
  "PAKISTAN",
  "PALAU",
  "PALESTINA",
  "PANAMA",
  "PAPUA NUOVA GUINEA",
  "PARAGUAY",
  "POLONIA",
  "PERU’",
  "PORTOGALLO",
  "QATAR",
  "REGNO UNITO",
  "REPUBBLICA CECA",
  "REPUBBLICA CENTRAFRICANA",
  "REPUBBLICA DOMINICANA",
  "ROMANIA",
  "RUANDA",
  "SAINT KITTS & NEVIS",
  "SAINT LUCIA",
  "SAINT VINCENT AND GRENADINE",
  "SAMOA",
  "SAN MARINO",
  "SANTA SEDE",
  "SAO TOME’ E PRINCIPE",
  "SENEGAL",
  "SERBIA",
  "SEYCHELLES",
  "SIERRA LEONE",
  "SINGAPORE",
  "SIRIA",
  "SLOVACCHIA",
  "SLOVENIA",
  "SOMALIA",
  "SPAGNA",
  "SRI LANKA",
  "STATI UNITI D’AMERICA",
  "SUDAFRICA",
  "STATI FEDERATI DI MICRONESIA",
  "SUDAN",
  "SUD SUDAN",
  "SURINAME",
  "SVEZIA",
  "SVIZZERA",
  "TAGIKISTAN",
  "TAIWAN (Repubblica di Cina)",
  "TANZANIA",
  "THAILANDIA",
  "TIMOR EST (Repubblica democratica di)",
  "TOGO",
  "TONGA",
  "TRINIDAD E TOBAGO",
  "TUNISIA",
  "TURCHIA",
  "TURKMENISTAN",
  "TUVALU",
  "UCRAINA",
  "UGANDA",
  "UNGHERIA",
  "URUGUAY",
  "UZBEKISTAN",
  "VANUATU",
  "VENEZUELA",
  "VIETNAM",
  "ZAMBIA",
  "ZIMBABWE",
] as const;

type NationalityOption = (typeof NATIONALITY_OPTIONS)[number];

export const NATIONALITY_SET = new Set<string>(NATIONALITY_OPTIONS);

function normalizeNationalityKey(value: string): string {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[’'`]/g, " ")
    .replace(/&/g, " e ")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

const NATIONALITY_BY_NORMALIZED_KEY = new Map<string, NationalityOption>(
  NATIONALITY_OPTIONS.map((option) => [normalizeNationalityKey(option), option])
);

// Compatibility for values that already exist in imported or historic data.
const NATIONALITY_ALIASES = new Map<string, NationalityOption>([
  [normalizeNationalityKey("Antigua"), "ANTIGUA E BARBUDA"],
  [normalizeNationalityKey("Bielorussia"), "BELARUS"],
  [normalizeNationalityKey("Capo Verde"), "CABO VERDE"],
  [normalizeNationalityKey("Fiji"), "FIGI"],
  [normalizeNationalityKey("Kazakistan"), "KAZAKHSTAN"],
  [normalizeNationalityKey("Kenia"), "KENYA"],
  [normalizeNationalityKey("Kirghizistan"), "KYRGHIZISTAN"],
  [normalizeNationalityKey("Macedonia"), "MACEDONIA DEL NORD"],
  [normalizeNationalityKey("Malesia"), "MALAYSIA"],
  [normalizeNationalityKey("Moldavia"), "MOLDOVA"],
  [normalizeNationalityKey("Myanmar (Birmania)"), "MYANMAR"],
  [normalizeNationalityKey("Repubblica Centro Africana"), "REPUBBLICA CENTRAFRICANA"],
  [normalizeNationalityKey("Repubblica Democratica del Congo"), "CONGO (R.D)"],
  [normalizeNationalityKey("Russia"), "FEDERAZIONE RUSSA"],
  [normalizeNationalityKey("Saint Vincent e Grenadine"), "SAINT VINCENT AND GRENADINE"],
  [normalizeNationalityKey("Salomone"), "ISOLE SALOMONE"],
  [normalizeNationalityKey("St.Christopher (Kitts) e Nevis"), "SAINT KITTS & NEVIS"],
  [normalizeNationalityKey("Sud Africa"), "SUDAFRICA"],
  [normalizeNationalityKey("Swaziland"), "ESWATINI"],
  [normalizeNationalityKey("Taiwan"), "TAIWAN (Repubblica di Cina)"],
  [normalizeNationalityKey("Timor Est"), "TIMOR EST (Repubblica democratica di)"],
]);

export function normalizeNationality(value: string | null | undefined): NationalityOption | null {
  if (!value) return null;

  const normalizedKey = normalizeNationalityKey(value);
  return (
    NATIONALITY_BY_NORMALIZED_KEY.get(normalizedKey) ??
    NATIONALITY_ALIASES.get(normalizedKey) ??
    null
  );
}
