const RAW_NATIONALITY_OPTIONS = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Angola",
  "Antigua",
  "Antille Olandesi",
  "Arabia Saudita",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Azerbaijan",
  "Azzorre",
  "Bahamas",
  "Bahrein",
  "Bangladesh",
  "Barbados",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bielorussia",
  "Bolivia",
  "Bosnia Erzegovina",
  "Botswana",
  "Brasile",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambogia",
  "Camerun",
  "Canarie",
  "Capo Verde",
  "Cayman",
  "Christmas",
  "Ciad",
  "Cile",
  "Cina",
  "Cipro",
  "Cocos",
  "Colombia",
  "Comore",
  "Congo",
  "Cook",
  "Corea del Nord e Sud",
  "Costa d'Avorio",
  "Costa Rica",
  "Croazia",
  "Cuba",
  "Dominica",
  "Ecuador",
  "Egitto",
  "El Salvador",
  "Emirati Arabi Uniti",
  "Eritrea",
  "Estonia",
  "Etiopia",
  "Fiji",
  "Filippine",
  "Gabon",
  "Gambia",
  "Georgia",
  "Ghana",
  "Giamaica",
  "Gibuti",
  "Giordania",
  "Grenada",
  "Guadalupa",
  "Guam",
  "Guatemala",
  "Guiana Francese",
  "Guinea",
  "Guinea Equatoriale",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Hawaii",
  "Honduras",
  "Hong Kong",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Israele",
  "Iugoslavia",
  "Kazakistan",
  "Kenia",
  "Kirghizistan",
  "Kiribati",
  "Kuwait",
  "Laos",
  "Lesotho",
  "Lettonia",
  "Libano",
  "Liberia",
  "Libia",
  "Lituania",
  "Macao",
  "Macedonia",
  "Madagascar",
  "Madeira",
  "Malawi",
  "Maldive",
  "Malesia",
  "Mali",
  "Marianne",
  "Marocco",
  "Marshall",
  "Martinica",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Messico",
  "Micronesia",
  "Moldavia",
  "Mongolia",
  "Montserrat",
  "Mozambico",
  "Myanmar (Birmania)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk",
  "Nuova Caledonia",
  "Nuova Zelanda",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua Nuova Guinea",
  "Paraguay",
  "Perù",
  "Pitcairn",
  "Polinesia Francese",
  "Polonia",
  "Porto Rico",
  "Qatar",
  "Repubblica Centro Africana",
  "Repubblica Democratica del Congo",
  "Repubblica Dominicana",
  "Reunion",
  "Romania",
  "Ruanda",
  "Russia",
  "Saint Lucia",
  "Saint Vincent e Grenadine",
  "Salomone",
  "Samoa",
  "Sant'Elena",
  "Sao Tomè e Principe",
  "Senegal",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Siria",
  "Somalia",
  "Sri Lanka",
  "St.Christopher (Kitts) e Nevis",
  "Sud Africa",
  "Sud Sudan",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Tagikistan",
  "Taiwan",
  "Tanzania",
  "Thailandia",
  "Timor Est",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad e Tobago",
  "Tunisia",
  "Turchia",
  "Turkmenistan",
  "Tuvalu",
  "Ucraina",
  "Uganda",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vergini (Isole)",
  "Vietnam",
  "Wake",
  "Wallis e Futuna",
  "Yemen",
  "Zambia",
  "Zimbabwe",
] as const;

const COLLATOR = new Intl.Collator("it", { sensitivity: "base" });

export const NATIONALITY_OPTIONS = [
  "Italia",
  ...[...RAW_NATIONALITY_OPTIONS].sort((a, b) => COLLATOR.compare(a, b)),
] as const;

export const NATIONALITY_SET = new Set<string>(NATIONALITY_OPTIONS);
